config/routes.rb
Astra::Application.routes.draw do  
  devise_for :admins, skip: [:registrations, :passwords],
    controllers: { :sessions => 'admin/sessions' }

  namespace :admin do
    resources :dashboards, path: '', only: [:index] do
      collection do
        get :completed
        get :vk_friends
        get :image_resize
        post :image_resize_run
      end
    end

    resources :categories
    resources :products do
      post :change_position, on: :collection
      get :upload_vk_photo
    end
    resources :cloths
    resources :categories_cloths
    resources :orders, except: [:show, :new, :create] do
      get :completed
    end
    resources :feedbacks, only: [:index, :destroy]
    resources :lookbook_categories do
      resources :lookbook_items, except: [:show] do
        post :save_position, on: :collection
        get :show_hide
      end
    end
    resources :statistics, only: :index

    namespace :instagram do
      get :callback
      get :connect
      get :limits

      post :init_subscribers
      get :get_likes      

      get :index
    end
  end

  namespace :page, path: '' do
    get :about
    get :contacts
    get :cart
    get :thankyou
    get :test
  end
  

  resources :lookbooks, only: [:index, :show], path: 'lookbook' do
    get :index_2, on: :collection
    get :index_3, on: :collection


  end
  resources :categories, only: [:show], path: ''
  resources :products, only: [:show]
  resources :orders, only: [:create] do
    get :add_item
    get :remove_item

  end
  resources :feedbacks, only: [:create]

  root 'page#home'
end

app/views/admin/partials/_form_errors.haml
#error_explanation.thumbnail
  .caption
    .lead
      = I18n.t(:errors_prohibited_this_record_from_being_saved, count: f.object.errors.count)
    %ul
      - f.object.errors.full_messages.each do |msg|
        %li= msg

app/views/admin/partials/_header.haml
%nav.navbar.navbar-light.bg-faded
  = link_to 'Astra', root_path, class: 'navbar-brand'
  %ul.nav.navbar-nav
    %li{ class: "nav-item #{active_menu('admin/dashboards')}" }
      = link_to 'Dashboard', admin_dashboards_path, class: 'nav-link'

    %li{ class: "nav-item #{active_menu('admin/dashboards')}" }
      = link_to 'Выполненные', completed_admin_dashboards_path, class: 'nav-link'

  /   %li{ class: "nav-item #{active_menu('admin/categories')}" }
  /     = link_to 'Категории', admin_categories_path, class: 'nav-link'

  /   %li{ class: "nav-item #{active_menu('admin/products')}" }
  /     = link_to 'Продукты', admin_products_path, class: 'nav-link'

  /   %li{ class: "nav-item #{active_menu('admin/lookbook_categories')}" }
  /     = link_to 'Gallery', admin_lookbook_categories_path, class: 'nav-link'

  /   -# %li{ class: active_menu('admin/feedbacks') }
  /   -#   = link_to 'Обратная связь', admin_feedbacks_path

  /   -# %li{ class: active_menu('admin/statistics') }
  /   -#   = link_to 'Статистика', admin_statistics_path

  /   %li{ class: active_menu('admin/vk_friends_admin_dashboards') }
  /     = link_to 'Друзья VK', vk_friends_admin_dashboards_path

    

  /   / %li.navbar-toggler{ class: active_menu(['admin/nup/feedbacks', 'admin/nup/feedback_subscribers', 'admin/nup/faqs'])  }
  /   /   %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
  /   /     Прочее
  /   /     %b.caret
  /   /     %ul.dropdown-menu
  /   %li{ class: "nav-item #{active_menu('admin/prepare_image')}" }
  /     = link_to 'Instagram', admin_instagram_index_path, class: 'nav-link'

  /   %li{ class: "nav-item #{active_menu('admin/prepare_image')}" }
  /     = link_to 'Img pre', image_resize_admin_dashboards_path, class: 'nav-link'

  / %ul.nav.navbar-nav.pull-right
  /   %li.nav-item
  /     = link_to 'выйти', destroy_admin_session_path, method: :delete, class: 'nav-link'