config/routes.rb
Astra::Application.routes.draw do  
  devise_for :admins, skip: [:registrations, :passwords],
    controllers: { :sessions => 'admin/sessions' }

  namespace :admin do
    resources :dashboards, path: '', only: [:index] do
      collection do
        get :completed
        get :vk_friends
        get :image_resize
        post :image_resize_run
      end
    end

    resources :categories
    resources :products do
      post :change_position, on: :collection
      get :upload_vk_photo
    end
    resources :cloths
    resources :categories_cloths
    resources :orders, except: [:show, :new, :create] do
      get :completed
    end
    resources :feedbacks, only: [:index, :destroy]
    resources :lookbook_categories do
      resources :lookbook_items, except: [:show] do
        post :save_position, on: :collection
        get :show_hide
      end
    end
    resources :statistics, only: :index

    namespace :instagram do
      get :callback
      get :connect
      get :limits

      post :init_subscribers
      get :get_likes      

      get :index
    end
  end

  namespace :page, path: '' do
    get :about
    get :contacts
    get :cart
    get :thankyou
    get :test
  end
  

  resources :lookbooks, only: [:index, :show], path: 'lookbook' do
    get :index_2, on: :collection
    get :index_3, on: :collection


  end
  resources :categories, only: [:show], path: ''
  resources :products, only: [:show]
  resources :orders, only: [:create] do
    get :add_item
    get :remove_item

  end
  resources :feedbacks, only: [:create]

  root 'page#home'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_attached_file :image, styles: { preview: '533x300#' } #16:9
  has_many :products
  has_many :about_product_images
  accepts_nested_attributes_for :about_product_images, reject_if: :all_blank, allow_destroy: true
  has_and_belongs_to_many :cloths

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }

  validates :title, presence: true

  scope :show, -> { where(show: true) }
  scope :by_pos, -> { order(:pos) }
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  layout 'admin'

  def index
    unless current_admin.present?
      redirect_to new_admin_session_path
    end

    @orders = Order.where(complete: false).order(created_at: :desc)
  end

  def completed
    @orders = Order.where(complete: true).order(created_at: :desc)
    render 'index'
  end

  def vk_friends
    if params[:id].present?
      @users = PotentialFriends.get_some(params[:id], 500, params[:page].to_i)
    end
  end

  def image_resize
  end

  def image_resize_run
    @image_resize = ImageResize.create(image_resize_params)
    ImageResize.where.not(id: @image_resize.id).destroy_all
    render :image_resize
  end

  private
    def image_resize_params
      params.require(:image_resize).permit(:size, :image)
    end
  
end

app/views/admin/dashboards/image_resize.haml
- if @image_resize.present?
  .row
    .col-xs-6.col-xs-offset-3
      = image_tag @image_resize.image(:thumb), class: 'img-responsive'
= form_for([:admin, ImageResize.new], url: image_resize_run_admin_dashboards_path, html: {role: 'form', class: 'form-horizontal'}) do |f|
  %br
  .row
    .col-xs-6.col-xs-offset-3
      .form-group
        .col-sm-2.control-label
          = f.label :size
        .col-sm-10
          = f.text_field :size, class: 'form-control'
          %small 700x700#

      .form-group
        .col-sm-2.control-label
          = f.label :image
        .col-sm-10
          = f.file_field :image

  .row
    .form-group.text-center
      = f.submit 'Сохранить', class: 'btn btn-success'

app/views/admin/dashboards/index.haml
.page-header
  %h1
    Заказы

.row
  %table.table.table-hover
    / %thead
    /   %tr
    /     %th Фото
    /     %th Информация о заказе
    /     %th Информация о заказчике
    /     %th

    %tbody
      - @orders.each do |order|
        %tr{ class: order_class(order) }
          %td{ style: 'width: 15%' }
            - if order.product_ids.present?
              - Product.where(id: order.product_ids).each do |product|
                = image_tag product.first_image
            - else
              = image_tag order.product.first_image if order.product.present?
          %td
            %b ##{order.id}
            = Product.where(id: order.product_ids).pluck(:title).join(', ')
            %br
            %small
              = time_tag order.created_at, format: :short
              %sup #{time_ago_in_words(order.created_at).gsub('около', 'ок.').gsub(/(яцев|яца)/, '.')} назад

            - if order.details.present?
              %br
              %b Детали:
              = raw link_finder(order.details)
            - if order.mark.present?
              %br
              %b Пометки:
              = order.mark
    
          %td
            %small= phone_tag order.phone
            %br
            = order.name

          %td
            = link_to admin_order_completed_path(order), class: 'btn btn-success' do
              .icon-cut

            = link_to edit_admin_order_path(order), class: 'btn btn-default' do
              .icon-pencil

            / = link_to admin_order_path(order), method: :delete, data: { confirm: 'Are you sure?' }, class: 'uk-button uk-button-mini uk-button-danger' do
            /   .uk-icon-times

app/views/admin/dashboards/vk_friends.haml
%h1 Links =)
= form_tag vk_friends_admin_dashboards_path, method: :get do
  = text_field_tag :id, params[:id]
  = submit_tag :submit

  %ul
    %li 84735
    %li 8011445


- if @users
  = link_to 'next page', vk_friends_admin_dashboards_path(page: params[:page].to_i + 1, id: params[:id]), class: 'pull-right'

  - @users.each_slice(10) do |slice|
    %ol 
      - slice.each do |user|
        %li
          = link_to "#{user.first_name} #{user.last_name}", "https://vk.com/id#{user.uid}", target: '_blank'
          / = user.mutual
    %br