config/routes.rb
Astra::Application.routes.draw do  
  devise_for :admins, skip: [:registrations, :passwords],
    controllers: { :sessions => 'admin/sessions' }

  namespace :admin do
    resources :dashboards, path: '', only: [:index] do
      collection do
        get :completed
        get :vk_friends
        get :image_resize
        post :image_resize_run
      end
    end

    resources :categories
    resources :products do
      post :change_position, on: :collection
      get :upload_vk_photo
    end
    resources :cloths
    resources :categories_cloths
    resources :orders, except: [:show, :new, :create] do
      get :completed
    end
    resources :feedbacks, only: [:index, :destroy]
    resources :lookbook_categories do
      resources :lookbook_items, except: [:show] do
        post :save_position, on: :collection
        get :show_hide
      end
    end
    resources :statistics, only: :index

    namespace :instagram do
      get :callback
      get :connect
      get :limits

      post :init_subscribers
      get :get_likes      

      get :index
    end
  end

  namespace :page, path: '' do
    get :about
    get :contacts
    get :cart
    get :thankyou
    get :test
  end
  

  resources :lookbooks, only: [:index, :show], path: 'lookbook' do
    get :index_2, on: :collection
    get :index_3, on: :collection


  end
  resources :categories, only: [:show], path: ''
  resources :products, only: [:show]
  resources :orders, only: [:create] do
    get :add_item
    get :remove_item

  end
  resources :feedbacks, only: [:create]

  root 'page#home'
end

app/models/lookbook_category.rb
class LookbookCategory < ActiveRecord::Base
  scope :show, -> { where(show: true) }

  validates :title, :overview, presence: true
  validates :image, attachment_presence: true

  has_many :lookbook_items

  has_attached_file :image, styles: {galery: "1400x658#"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/admin/lookbook_categories_controller.rb
class Admin::LookbookCategoriesController < Admin::BaseController
  def show
    @lookbook_items = LookbookCategory.find(params[:id]).lookbook_items
  end

protected
  def collection
    LookbookCategory.order(created_at: :desc)
  end

  def lookbook_category_params
    params.require(:lookbook_category).permit(:title, :overview, :image, :show, :created_at)
  end
end

app/views/admin/lookbook_categories/_form.haml
.row
  .col-xs-8.col-xs-offset-2
    = form_for([:admin, resource], html: {role: 'form'}) do |f|
      - if resource.errors.present?
        = render 'errors', errors: resource.errors

      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'

      .form-group
        = f.label :overview
        = f.text_area :overview, class: 'form-control'

      .form-group
        .row
          .col-xs-8
            = f.label :image
            = f.file_field :image
          .col-xs-4
            - if f.object.image.present?
              = image_tag f.object.image.url, class: 'pull-right img-responsive'

      .form-group
        = f.label :show
        = f.check_box :show

      .form-group
        = f.label :created_at
        = f.date_field :created_at

      .form-group
        = f.submit 'Сохранить', class: 'btn btn-success'

app/views/admin/lookbook_categories/_lookbook_item.haml
- controls = ''
- controls += link_to('edit', edit_admin_lookbook_category_lookbook_item_path(resource, item))
- controls += ' '
- controls += link_to("#{item.show ? 'show' : 'hide'}",admin_lookbook_category_lookbook_item_show_hide_path(resource, item), remote: true)
- controls += ' '
- controls += lookbook_background_position(item.background_position)
- controls += ' '
- controls += link_to('удалить', admin_lookbook_category_lookbook_item_path(resource, item), confirm: 'Are you sure?', method: 'delete')


- if item.position.present?
  %li{'data-id' => "#{item.id}", "data-col" => "#{item.position[:col]}", "data-row" => "#{item.position[:row]}", "data-sizex" => "#{item.position[:size_x]}", "data-sizey" => "#{item.position[:size_y]}", style: "background-image: url(#{lookbook_background_size(item)}); background-position: #{lookbook_background_position(item.background_position)};"}
    = item.position
    = raw controls


- else
  %li{'data-id' => "#{item.id}", "data-col" => '6', "data-row" => "1", "data-sizex" => "1", "data-sizey" => "1", style: "background-image: url(#{item.image(:preview)})"}
    = raw controls

app/views/admin/lookbook_categories/index.haml
.page-header
  %h1
    Категории
    = link_to '+ добавить', new_resource_url, class: 'btn btn-default pull-right'


- if collection.present?
  %table.table
    %thead
      %tr
        %th id
        %th overview
        %th image
        %th

    %tbody
      - collection.each do |category|
        %tr
          %td= category.id
          %td
            %b= category.title
            %br
            = category.overview
            %br
          %td
            = image_tag(category.image.url(:galery))
          %td
            = time_tag category.created_at
            .pull-right.controls
              = link_to 'редактировать раздел', edit_resource_path(category), class: 'btn btn-default btn-xs'
              = link_to 'редактировать элементы раздела', resource_path(category), class: 'btn btn-default btn-xs'
              = link_to 'удалить', resource_path(category), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs'

app/views/admin/lookbook_categories/show.haml
.page-header
  %h1
    LookBook
    = link_to 'save position', '#', id: 'js-seralize', class: 'btn btn-default pull-right'
    = link_to '+ new item', new_admin_lookbook_category_lookbook_item_path(resource.id), class: 'btn btn-default pull-right'

.row
  .col-xs-12.gridster
    %ul
      - @lookbook_items.each do |item|
        = render 'lookbook_item', item: item